### ISSUE TITLE
(Question) I/O Problem with Canon EOS 5DS

### ISSUE THREAD

**Issue by sinhau** [jim-easterbrook/python-gphoto2#23]
Hi,

I'm running a python script (on Ubuntu 14.04) that uses gphoto2 to fire 2 Canon EOS 5DS simultaneously and then save the picture on the computer.  It seems to work well for a minute or so, but then I get a "error: [-7] I/O problem" from both cameras when issues the capture command (gp.check_result(gp.gp_camera_capture(self.camera, gp.GP_CAPTURE_IMAGE, self.context))).  Has anyone else also encountered I/O problems with EOS 5DS?  Fyi, I'm using 2 USB 3.0 micro cable plugged into a usb 3.0 powered hub.  

Thanks!

PS - I posted this issue on the gphoto2 mailing list also.  Just wanted to get an opinion on this channel as well.

**Comment by jim-easterbrook** [comment]
I don't know the answer, but I'd start by finding out if the problem also happens if you use just one camera. If it only happens when two cameras are in use then maybe there's some sort of bus conflict or something. Are you using multiple threads or multiple processes? I don't know if libgphoto2 is thread-safe.

**Comment by JonathanBaurer** [comment]
For any future users who have this problem, I spent days trying to figure out what was going on when my Canon EOS 6D  kept running into the mysterious I/O problem while copying files. Sometimes it would happen after 5 images were copied, and sometimes I could get through up to 70 before the issue occurred. This happened to me using both python-gphoto2 and the gphoto2 command line utility.

Turns out, gphoto2 has some problems with USB 3.0 ports, that can cause this issue (since the 6D only has 2.0 capability, it is best to use a USB 2.0 port).  My problem, however, came from the fact that I was running gphoto2 in Ubuntu through a VM on Windows, and had not enabled USB 2.0 support. I downloaded the VirtualBox extension pack, enabled 2.0, and haven't seen this issue since.

Hope this helps any future users!
