### ISSUE TITLE
How to use bulb mode? 

### ISSUE THREAD

**Issue by 2dal** [jim-easterbrook/python-gphoto2#91]
Using python 3.6 libgphoto2 version 2.5.22-1 and python-gphoto version 2.0.0 

I'm having difficulty finding the right syntax for having exposure time (bulb mode) longer than my cameras maximum 30 seconds in the python-gphoto. This works fine in libgphoto2, where the syntax is 

gphoto2 --set-config bulb=1 --wait-event=300s --set-config bulb=0 --wait-event-and-download=2s

**Comment by 2dal** [comment]
I think that is the way to go. But I'm having trouble finding the correct syntax for it. I've searched through the repository a couple of times and haven't been able to find any way to set the camera to bulb mode

**Comment by jim-easterbrook** [comment]
The camera-config-gui.py example will show all the configuration options available for your camera, as will the `gphoto2 --list-config` command line program. Several of the example programs demonstrate setting camera config, set-capture-target.py is probably the simplest.

**Comment by programatt** [comment]
@2dal if you're interested I was able to figure out how to do a bulb exposure using the eosremoterelease config value. https://gist.github.com/programatt/1d1f4987770ed8ecf5327df0ae561d0a I'm just doing a sleep for the length of the exposure, the problem is that CameraEventType in gphoto doesn't expose an event to know how long the shutter is held down for. Feel free to use this if you still need/want it!
